
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::832510228841:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-c6RIKQn8V1kT
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - pod-reader
      userarn: arn:aws:iam::832510228841:user/raghu
      username: raghu
    - groups:
      - pod-reader
      userarn: arn:aws:iam::832510228841:user/somu
      username: somu
    - groups:
      - pod-reader
      userarn: arn:aws:iam::832510228841:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-27T15:48:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1251"
  uid: 594189d0-9179-40d4-ab7c-eb98a941d5ab
