apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::832510228841:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-0Jllw31OKg7g
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - pod-reader
      userarn: arn:aws:iam::832510228841:user/raghu
      username: raghu
      arn:aws:iam::832510228841:user/somu
    - groups:
      - pod-reader
      userarn: arn:aws:iam::832510228841:user/somu
      username: somu
kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-24T12:05:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1224"
  uid: a054eadf-99fb-48b9-b32b-a05894ce0511
